# File generated by cdo from CONTRIBUTING.md; DO NOT EDIT.

SHELL=bash
.SHELLFLAGS=-e -o pipefail -c

.PHONY: __help__
__help__:
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Targets:'
	@echo '  build    Build the executable binary'
	@echo '  ci       Run all ci-relevant tasks'
	@echo '  clean    Delete the build directory'
	@echo '  coverage View the test coverage report'
	@echo '  lint     Run the linter'
	@echo '  makefile Generate Makefile'
	@echo '  readme   Update the README.md'
	@echo '  snapshot Creating an executable binary with a snapshot version'
	@echo '  test     Run the tests'

# Build the executable binary
.PHONY: build
build: 
	@(\
		go build -ldflags="-w -s" -o build/cdo .;\
	)

# Run all ci-relevant tasks
.PHONY: ci
ci: lint test build snapshot

# Delete the build directory
.PHONY: clean
clean: 
	@(\
		rm -rf build;\
	)

# View the test coverage report
.PHONY: coverage
coverage: test
	@(\
		go tool cover -html=coverage.txt;\
	)

# Run the linter
.PHONY: lint
lint: 
	@(\
		golangci-lint run;\
	)

# Generate Makefile
.PHONY: makefile
makefile: 
	@(\
		cdo --makefile Makefile;\
	)

# Update the README.md
.PHONY: readme
readme: 
	@(\
		mdcode update;\
	)

# Creating an executable binary with a snapshot version
.PHONY: snapshot
snapshot: 
	@(\
		rm -f build/cdo;\
		goreleaser build --snapshot --clean --single-target -o build/cdo;\
	)

# Run the tests
.PHONY: test
test: 
	@(\
		go test -count 1 -race -coverprofile=coverage.txt ./...;\
	)

